from __future__ import unicode_literals

# state constants
STATE_INIT = 0
STATE_ACQUIRING = 1
STATE_ACQUIRED = 2
STATE_RELEASING = 3
STATE_RELEASED = 4
STATE_ACQUIRING_TIMEDOUT = 5
STATE_ACQUIRED_TIMEDOUT = 6
STATE_ACQUIRING_RETRYING = 7
STATE_RELEASING_RETRYING = 8
STATE_ACQUIRING_EXCEPTION = 9

OK_TO_ACQUIRE = {STATE_INIT, STATE_RELEASED}
OK_TO_RELEASE = {STATE_ACQUIRED}
